@echo off
del opentx.hex
cls
cd sources
path ..\avr-gcc\bin;..\avr-gcc\utils\bin

make clean

make ^
 ^
PCB=MEGA2560 ^
LCD=SSD1306 ^
 ^
PWRMANAGE=NO ^
SHUTDOWN_CONFIRMATION=NO ^
 ^
EXT=FRSKY ^
FRSKY_HUB=YES ^
GPS=NO ^
VARIO=NO ^
 ^
SDCARD=YES ^
RTCLOCK=YES ^
AUDIO=NO ^
VOICE=JQ6500 ^
HAPTIC=NO ^
 ^
DEFAULT_MODE=1 ^
NAVIGATION=ROTENC ^
DBLKEYS=YES ^
AUTOSWITCH=YES ^
AUTOSOURCE=YES ^
 ^
HELI=YES ^
FLIGHT_MODES=YES ^
CURVES=YES ^
GVARS=YES ^
OFFSET_ON_INPUT=YES ^
PPM_CENTER_ADJUSTABLE=YES ^
PPM_LIMITS_SYMETRICAL=YES ^
PPM_UNIT=PERCENT_PREC1 ^
 ^
TRANSLATIONS=EN ^
TTS=EN ^
FONT=STD ^
SPLASH=YES ^
TEMPLATES=NO ^
BATTGRAPH=NO ^
THR_TRACE=YES ^
EEPROM_PROGRESS_BAR=NO

pause
copy opentx.hex ..\opentx.hex
make clean
